image: kaiwinter/docker-java8-maven

stages:
  - compile
  - test
  - checkstyle

build:
  stage: compile
  script:
    - mvn compiler:testCompile

test:
  stage: test
  script:
    - mvn surefire:test

checkstyle:
  stage: checkstyle
  script:
    - mvn checkstyle:check
