image: maven:3.6.0-jdk-11

stages:
  - compile
  - test
  - checkstyle

build:
  stage: compile
  script:
    - mvn compiler:compile

test:
  stage: test
  script:
    - mvn test -Dcheckstyle.skip
    - mvn jacoco:report
  artifacts:
    paths:
      - build/site/jacoco/

checkstyle:
  stage: checkstyle
  script:
    - mvn checkstyle:check
