image: maven:3.6-jdk-8-alpine

stages:
  - compile
  - test
  - checkstyle

build:
  stage: compile
  script:
    - mvn compiler:compile

test:
  stage: test
  script:
    - mvn surefire:test

checkstyle:
  stage: checkstyle
  script:
    - mvn checkstyle:check
