image: kaiwinter/docker-java8-maven

stages:
  - compile
  - test
  - checkstyle

build:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

checkstyle:
  stage: checkstyle
  script:
    - mvn validate
